from pathlib import Path

path = Path("tests/browser/growth-os.browser.spec.ts")
text = path.read_text()

old = '''      "/v1/analytics/metrics", "/v1/content", "/v1/publication-intents",\n'''
new = '''      "/v1/analytics/metrics", "/v1/analytics/anomalies", "/v1/content", "/v1/publication-intents",\n'''
if old not in text:
    raise SystemExit("signed-out analytics anchor not found")
text = text.replace(old, new, 1)

old = '''    if (mode === "authenticated" && path === "/v1/analytics/metrics") {\n      return json(route, 200, {\n        status: "ok",\n        from: "2026-09-08T00:00:00.000Z",\n        to: "2026-09-15T00:00:00.000Z",\n        metrics\n      });\n    }\n\n'''
new = '''    if (mode === "authenticated" && path === "/v1/analytics/metrics") {\n      return json(route, 200, {\n        status: "ok",\n        from: "2026-09-08T00:00:00.000Z",\n        to: "2026-09-15T00:00:00.000Z",\n        metrics\n      });\n    }\n\n    if (mode === "authenticated" && path === "/v1/analytics/anomalies") {\n      return json(route, 200, {\n        status: "ok",\n        from: "2026-09-08T00:00:00.000Z",\n        to: "2026-09-15T00:00:00.000Z",\n        anomalies: []\n      });\n    }\n\n    if (mode === "authenticated" && path === "/v1/copilot/query" && route.request().method() === "POST") {\n      return json(route, 200, {\n        status: "ok",\n        reply: {\n          mode: "evidence_grounded",\n          intent: "evidence",\n          answer: "The controlled opportunity is supported by one persisted evidence reference. This browser fixture proves only the Copilot interface and evidence boundary.",\n          citations: [{\n            kind: "evidence",\n            ref: "browser-quality-controlled-fixture",\n            label: "owned evidence"\n          }],\n          workspace_pulse: {\n            opportunities: 1,\n            insights: 0,\n            metric_rows: metrics.length,\n            quality_alerts: 0,\n            experiments: 0,\n            automation_needs_attention: 0,\n            automation_kill_switch: false\n          },\n          suggested_prompts: ["What evidence supports the top opportunity?"],\n          limitations: [\n            "Answers use only persisted data available to the current workspace.",\n            "Correlation is not presented as confirmed causality.",\n            "Copilot does not publish or execute provider actions; those remain behind existing approval and Autopilot controls."\n          ]\n        }\n      });\n    }\n\n'''
if old not in text:
    raise SystemExit("analytics handler anchor not found")
text = text.replace(old, new, 1)

anchor = '''test("authenticated Radar shell remains accessible across desktop and mobile", async ({ page }) => {\n  const unhandled = await mockApi(page, "authenticated");\n  await page.goto("/");\n\n  await expect(page.getByRole("heading", { name: "See what is beginning to move." })).toBeVisible();\n  await expect(page.getByText("Browser Quality Workspace")).toBeVisible();\n  await expect(page.getByRole("button", { name: /US opportunity/i })).toBeVisible();\n  await expect(page.getByRole("heading", { name: "Instagram · US" })).toBeVisible();\n  await expect(page.getByText("browser-quality-controlled-fixture")).toBeVisible();\n\n  await expectNoHorizontalOverflow(page);\n  await expectNoSeriousAccessibilityViolations(page);\n\n  await page.setViewportSize({ width: 390, height: 844 });\n  await expect(page.getByRole("heading", { name: "See what is beginning to move." })).toBeVisible();\n  await expectNoHorizontalOverflow(page);\n  await expectNoSeriousAccessibilityViolations(page);\n  expect(unhandled).toEqual([]);\n});\n\n'''
addition = anchor + '''test("Copilot stays evidence-grounded, accessible and read-only in the authenticated shell", async ({ page }) => {\n  const unhandled = await mockApi(page, "authenticated");\n  const copilotWrites: Record<string, unknown>[] = [];\n  await page.route("**/v1/copilot/query", async (route, request) => {\n    if (request.method() !== "POST") return route.fallback();\n    copilotWrites.push(request.postDataJSON());\n    return json(route, 200, {\n      status: "ok",\n      reply: {\n        mode: "evidence_grounded",\n        intent: "evidence",\n        answer: "The controlled opportunity is supported by one persisted evidence reference. No provider action is executed.",\n        citations: [{ kind: "evidence", ref: "browser-quality-controlled-fixture", label: "owned evidence" }],\n        workspace_pulse: {\n          opportunities: 1, insights: 0, metric_rows: 0, quality_alerts: 0,\n          experiments: 0, automation_needs_attention: 0, automation_kill_switch: false\n        },\n        suggested_prompts: ["What evidence supports the top opportunity?"],\n        limitations: [\n          "Answers use only persisted data available to the current workspace.",\n          "Correlation is not presented as confirmed causality.",\n          "Copilot does not publish or execute provider actions; those remain behind existing approval and Autopilot controls."\n        ]\n      }\n    });\n  });\n\n  await page.goto("/");\n  const toggle = page.getByRole("button", { name: /Copilot.*Evidence grounded/i });\n  await expect(toggle).toBeVisible();\n  await toggle.click();\n  await expect(page.getByRole("heading", { name: "Ask what the evidence supports" })).toBeVisible();\n  await page.getByRole("button", { name: "What evidence supports the top opportunity?", exact: true }).click();\n  await expect(page.getByText("The controlled opportunity is supported by one persisted evidence reference. No provider action is executed.", { exact: true })).toBeVisible();\n  await expect(page.getByText("browser-quality-controlled-fixture", { exact: true })).toBeVisible();\n  expect(copilotWrites).toEqual([{ message: "What evidence supports the top opportunity?" }]);\n\n  await expectNoHorizontalOverflow(page);\n  await expectNoSeriousAccessibilityViolations(page);\n  await page.setViewportSize({ width: 390, height: 844 });\n  await expectNoHorizontalOverflow(page);\n  await expectNoSeriousAccessibilityViolations(page);\n  expect(unhandled).toEqual([]);\n});\n\n'''
if anchor not in text:
    raise SystemExit("authenticated radar test anchor not found")
text = text.replace(anchor, addition, 1)
path.write_text(text)

memory = Path("docs/PROJECT_EXECUTION_MEMORY.md")
entry = '''\n- O fechamento adiciona cobertura browser explícita para o Copilot evidence-grounded e adiciona `/v1/analytics/anomalies` ao mock fail-closed do browser gate, garantindo que a nova leitura de alertas de qualidade não seja mascarada como request desconhecido.\n'''
current = memory.read_text()
if "cobertura browser explícita para o Copilot" not in current:
    memory.write_text(current + entry)
